class QuestState:
    CREATED = "CREATED"
    INTRO_PLAYING = "INTRO_PLAYING"
    GATE_LOCKED = "GATE_LOCKED"
    GATE_UNLOCKED = "GATE_UNLOCKED"
    WELCOME_SHOWN = "WELCOME_SHOWN"
    REC_VIDEO1_PENDING = "REC_VIDEO1_PENDING"
    REC_VIDEO1_RECORDING = "REC_VIDEO1_RECORDING"
    REC_VIDEO1_UPLOADING = "REC_VIDEO1_UPLOADING"
    REC_VIDEO1_COMPLETE = "REC_VIDEO1_COMPLETE"
    WALL_OPENED = "WALL_OPENED"
    REC_VIDEO2_PENDING = "REC_VIDEO2_PENDING"
    DIAGON_ALLEY = "DIAGON_ALLEY"
    PLATFORM_TICKET = "PLATFORM_TICKET"
    TRAIN_JOURNEY = "TRAIN_JOURNEY"
    CASTLE_REVEAL = "CASTLE_REVEAL"
    SORTING_HAT = "SORTING_HAT"
    QUEST_HUB = "QUEST_HUB"
    LEVEL_1_COMPLETE = "LEVEL_1_COMPLETE"
    LEVEL_2_COMPLETE = "LEVEL_2_COMPLETE"
    LEVEL_3_COMPLETE = "LEVEL_3_COMPLETE"
    LEVEL_4_COMPLETE = "LEVEL_4_COMPLETE"
    FINAL_REVEAL = "FINAL_REVEAL"
    REWARD_UNLOCKED = "REWARD_UNLOCKED"
    REC_VIDEO2_STOPPED = "REC_VIDEO2_STOPPED"
    REC_VIDEO2_UPLOADING = "REC_VIDEO2_UPLOADING"
    REC_VIDEO2_COMPLETE = "REC_VIDEO2_COMPLETE"
    REC_REACTION_START = "REC_REACTION_START"
    REC_REACTION_UPLOADING = "REC_REACTION_UPLOADING"
    COMPLETED = "COMPLETED"

STATE_TRANSITIONS = {
    QuestState.CREATED: [QuestState.INTRO_PLAYING],
    QuestState.INTRO_PLAYING: [QuestState.GATE_LOCKED],
    QuestState.GATE_LOCKED: [QuestState.GATE_UNLOCKED],
    QuestState.GATE_UNLOCKED: [QuestState.WELCOME_SHOWN],
    QuestState.WELCOME_SHOWN: [QuestState.REC_VIDEO1_PENDING],
    QuestState.REC_VIDEO1_PENDING: [QuestState.REC_VIDEO1_RECORDING],
    QuestState.REC_VIDEO1_RECORDING: [QuestState.REC_VIDEO1_UPLOADING],
    QuestState.REC_VIDEO1_UPLOADING: [QuestState.REC_VIDEO1_COMPLETE],
    QuestState.REC_VIDEO1_COMPLETE: [QuestState.WALL_OPENED],
    QuestState.WALL_OPENED: [QuestState.REC_VIDEO2_PENDING],
    QuestState.REC_VIDEO2_PENDING: [QuestState.DIAGON_ALLEY],
    QuestState.DIAGON_ALLEY: [QuestState.PLATFORM_TICKET],
    QuestState.PLATFORM_TICKET: [QuestState.TRAIN_JOURNEY],
    QuestState.TRAIN_JOURNEY: [QuestState.CASTLE_REVEAL],
    QuestState.CASTLE_REVEAL: [QuestState.SORTING_HAT],
    QuestState.SORTING_HAT: [QuestState.QUEST_HUB],
    QuestState.QUEST_HUB: [QuestState.LEVEL_1_COMPLETE],
    QuestState.LEVEL_1_COMPLETE: [QuestState.LEVEL_2_COMPLETE],
    QuestState.LEVEL_2_COMPLETE: [QuestState.LEVEL_3_COMPLETE],
    QuestState.LEVEL_3_COMPLETE: [QuestState.LEVEL_4_COMPLETE],
    QuestState.LEVEL_4_COMPLETE: [QuestState.FINAL_REVEAL],
    QuestState.FINAL_REVEAL: [QuestState.REWARD_UNLOCKED],
    QuestState.REWARD_UNLOCKED: [QuestState.REC_VIDEO2_STOPPED],
    QuestState.REC_VIDEO2_STOPPED: [QuestState.REC_VIDEO2_UPLOADING],
    QuestState.REC_VIDEO2_UPLOADING: [QuestState.REC_VIDEO2_COMPLETE],
    QuestState.REC_VIDEO2_COMPLETE: [QuestState.REC_REACTION_START],
    QuestState.REC_REACTION_START: [QuestState.REC_REACTION_UPLOADING],
    QuestState.REC_REACTION_UPLOADING: [QuestState.COMPLETED],
}
